[package]
name = "assignlib"
version = "0.1.0"
authors = ["Shaistaaman <57103671+Shaistaaman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
myweather_app = {path="myweather_app"}